DROP TABLE IF EXISTS homework_group;
DROP TABLE IF EXISTS homework;
DROP TABLE IF EXISTS group_student;
DROP TABLE IF EXISTS group_course;
DROP TABLE IF EXISTS student_course;
DROP TABLE IF EXISTS teacher;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS course;

CREATE TABLE teacher (
  TEACHER_ID VARCHAR(10) NOT NULL ,
  TEACHER_NAME VARCHAR(10),
  SEX VARCHAR(2),
  PROFESSION VARCHAR(40),
  TELEPHONE VARCHAR(11),
  EMAIL VARCHAR(40),
  PASSWORD VARCHAR(40) NOT NULL ,
  PRIMARY KEY (TEACHER_ID)
);


CREATE TABLE student (
  STUDENT_ID VARCHAR(10) NOT NULL,
  STUDENT_NAME VARCHAR(10),
  CLASS_ID VARCHAR(20),
  SEX VARCHAR(2),
  ENTRANCE_DATE DATE,
  PASSWORD VARCHAR(40) NOT NULL,
  EMAIL VARCHAR(40),
  PRIMARY KEY (STUDENT_ID)
);


CREATE TABLE course(
  COURSE_ID INT(10) NOT NULL AUTO_INCREMENT,
  COURSE_NAME VARCHAR(40),
  TEACHER_ID VARCHAR(10) NOT NULL ,
  CAPACITY INT(3),
  GROUP_CAPACITY INT(3),
  GROUP_PREFIX VARCHAR(10),
  CREATE_TIME DATETIME NOT NULL ,
  PRIMARY KEY (COURSE_ID)
);


CREATE TABLE admin(
  ADMIN_ID VARCHAR(10) NOT NULL,
  ADMIN_NAME VARCHAR(10) ,
  PASSWORD VARCHAR(10) NOT NULL ,
  PRIMARY KEY (ADMIN_ID)
);


CREATE TABLE student_course(
  STUDENT_ID VARCHAR(10) NOT NULL ,
  COURSE_ID INT(10) NOT NULL ,
  GRADE INT(3),
  PRIMARY KEY (STUDENT_ID,COURSE_ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES student(STUDENT_ID),
  FOREIGN KEY (COURSE_ID) REFERENCES course(COURSE_ID)
);


CREATE TABLE group_course(
  GROUP_ID INT(10) NOT NULL AUTO_INCREMENT,
  COURSE_ID INT(10) NOT NULL ,
  NUM INT(3) ,
  NAME VARCHAR(20),
  LEADER_ID VARCHAR(10),
  GROUP_SCORE DOUBLE ,
  PRIMARY KEY (GROUP_ID),
  FOREIGN KEY (LEADER_ID) REFERENCES student(STUDENT_ID)
);


CREATE TABLE group_student(
  GROUP_ID INT(10) NOT NULL ,
  STUDENT_ID VARCHAR(10) NOT NULL,
  GRADE INT(3),
  PRIMARY KEY (GROUP_ID,STUDENT_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES group_course(GROUP_ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES student(STUDENT_ID)
);


CREATE TABLE homework(
  HOMEWORK_ID INT(10) NOT NULL AUTO_INCREMENT,
  COURSE_ID INT(10) NOT NULL ,
  CONTENT VARCHAR(100),
  RELEASETIME DATETIME NOT NULL ,
  DEADLINE DATETIME NOT NULL ,
  PRIMARY KEY (HOMEWORK_ID),
  FOREIGN KEY (COURSE_ID) REFERENCES course(COURSE_ID)
);


CREATE TABLE homework_group(
  GROUP_ID INT(10) NOT NULL ,
  HOMEWORK_ID INT(10) NOT NULL ,
  SUBMISSION_TIME DATETIME NOT NULL ,
  SCORE INT(3) ,
  COMMENT VARCHAR(100),
  FILEDIR VARCHAR(100),
  PRIMARY KEY (GROUP_ID,HOMEWORK_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES group_course(GROUP_ID),
  FOREIGN KEY (HOMEWORK_ID) REFERENCES homework(HOMEWORK_ID)
);
